name: workflow (collect data and create chart data)
on:
  workflow_dispatch:

  schedule:
    - cron: '00 14 * * *' # 23:00 in JST

jobs:
  collect_data_and_create_chart_data:
    name: job (collect data and create chart data)
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v3
        
      - name: Set up Python environment
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
        
      - name: Create and activate virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate

      - name: install python libraries
        run: pip3 install -r ./requirements.txt
        
      - name: get GitHub releases data (it-automation)
        continue-on-error: true
        run: python3 -m exastics.publish_github_api_releases exastro-suite it-automation

      - name: get GitHub releases data (oase)
        continue-on-error: true
        run: python3 -m exastics.publish_github_api_releases exastro-suite oase
        
      - name: get GitHub releases data (epoch)
        continue-on-error: true
        run: python3 -m exastics.publish_github_api_releases exastro-suite epoch
        
      - name: get GitHub releases data (Settings-CloudSystemTemplate-1st)
        continue-on-error: true
        run: python3 -m exastics.publish_github_api_releases exastro-suite Settings-CloudSystemTemplate-1st

      - name: get DockerHub repository data (it-automation)
        continue-on-error: true
        run: python3 -m exastics.publish_dockerhub_api_repository exastro it-automation

      - name: get DockerHub repository data (exastro-it-automation-migration)
        continue-on-error: true
        run: python3 -m exastics.publish_dockerhub_api_repository exastro exastro-it-automation-migration

      - name: get DockerHub repository data (oase)
        continue-on-error: true
        run: python3 -m exastics.publish_dockerhub_api_repository exastro oase

      - name: get DockerHub repository data (epoch)
        continue-on-error: true
        run: python3 -m exastics.publish_dockerhub_api_repository exastro epoch-ui

      - name: create GitHub download count chart data (it-automation)
        continue-on-error: true
        run: python3 -m exastics.create_chart_data_github_download_count ./it-automation/github-releases ./docs/assets/chart-data/it-automation-github-download-count.json
        
      - name: create GitHub download count chart data (oase)
        continue-on-error: true
        run: python3 -m exastics.create_chart_data_github_download_count ./oase/github-releases ./docs/assets/chart-data/oase-github-download-count.json

      - name: create GitHub download count chart data (epoch)
        continue-on-error: true
        run: python3 -m exastics.create_chart_data_github_download_count ./epoch/github-releases ./docs/assets/chart-data/epoch-github-download-count.json

      - name: create GitHub download count chart data (Settings-CloudSystemTemplate-1st)
        continue-on-error: true
        run: python3 -m exastics.create_chart_data_github_download_count ./Settings-CloudSystemTemplate-1st/github-releases ./docs/assets/chart-data/Settings-CloudSystemTemplate-1st-github-download-count.json

      - name: create DockerHub pull count chart data (it-automation)
        continue-on-error: true
        run: python3 -m exastics.create_chart_data_dockerhub_pull_count ./it-automation/dockerhub-repository/ ./docs/assets/chart-data/it-automation-dockerhub-pull-count.json

      - name: create DockerHub pull count chart data (exastro-it-automation-migration)
        continue-on-error: true
        run: python3 -m exastics.create_chart_data_dockerhub_pull_count ./exastro-it-automation-migration/dockerhub-repository/ ./docs/assets/chart-data/exastro-it-automation-dockerhub-pull-count.json

      - name: create DockerHub pull count chart data (oase)
        continue-on-error: true
        run: python3 -m exastics.create_chart_data_dockerhub_pull_count ./oase/dockerhub-repository/ ./docs/assets/chart-data/oase-dockerhub-pull-count.json

      - name: create DockerHub pull count chart data (epoch)
        continue-on-error: true
        run: python3 -m exastics.create_chart_data_dockerhub_pull_count ./epoch-ui/dockerhub-repository/ ./docs/assets/chart-data/epoch-ui-dockerhub-pull-count.json

      - name: push to GitHub
        run: |
            git config user.name github-actions
            git config user.email github-actions@github.com
            git add .
            git status
            git commit -m "GitHub Actions `TZ='Asia/Tokyo' date`"
            git push
