name: get Exastro Suite releases
on:
  workflow_dispatch:

  schedule:
    - cron: '30 14 * * *' # 23:30 in JST

jobs:
  get_releases:
    name: get releases
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v2

      - name: install python libraries
        run: pip3 install -r ./requirements.txt
        
      - name: get releases (it-automation)
        continue-on-error: true
        run: ./github-api-releases.py exastro-suite it-automation

      - name: get releases (oase)
        continue-on-error: true
        run: ./github-api-releases.py exastro-suite oase
        
      - name: get releases (Settings-CloudSystemTemplate-1st)
        continue-on-error: true
        run: ./github-api-releases.py exastro-suite Settings-CloudSystemTemplate-1st

      - name: create chart data (it-automation)
        continue-on-error: true
        run: ./create-chart-data-github-download-count.py ./it-automation/ ./docs/assets/chart-data/it-automation-github-download-count.json
        
      - name: create chart data (oase)
        continue-on-error: true
        run: ./create-chart-data-github-download-count.py ./oase/ ./docs/assets/chart-data/oase-github-download-count.json

      - name: create chart data (Settings-CloudSystemTemplate-1st)
        continue-on-error: true
        run: ./create-chart-data-github-download-count.py ./Settings-CloudSystemTemplate-1st/ ./docs/assets/chart-data/Settings-CloudSystemTemplate-1st-github-download-count.json

      - name: push to GitHub
        run: |
            git config user.name github-actions
            git config user.email github-actions@github.com
            git add .
            git commit -m "GitHub Actions `TZ='Asia/Tokyo' date`"
            git push
